### ISSUE TITLE
配置好的server对链接无法正常跳转

### ISSUE THREAD

**Issue by jaynlive** [tekintian/wechat_shop#1]

**Comment by tekintian** [comment]
需要提供详细的错误/BUG详情，

**Comment by lxyzai** [comment]
![image](https://user-images.githubusercontent.com/10511921/40178416-0154c0fa-5a14-11e8-95e5-78a73917e771.png)
我也是这样的，配置好server访问后台地址显示文件不存在，之前以为是伪静态的问题，改了之后还是不行，查了文件地址，Admin/Login/index.html确实没有文件

**Comment by tekintian** [comment]
URL ReWrite的问题，需要服务器支持 path_info模式，且必须设置Rewrite规则
