### ISSUE TITLE
有关 PATH_INFO 问题, 请求帮助

### ISSUE THREAD

**Issue by HolmesZhao** [tekintian/wechat_shop#4]
环境:
* centOS
* Nginx 1.14
* PHP 7.0
* 宝塔搭建的环境

问题:
访问`域名/Admin/Login` 出现 `404` 错误

描述:
在我的 MacOS 系统上, 本地跑没有问题成功了, 使用了 mamp 配置环境, 向 Nginx 中添加以下规则
```
#rewrite配置，很重要，如果你不知道你在做什么，请勿修改！！！
  if (!-e $request_filename) {
    rewrite "^/(.*)"  /index.php?s=/$1 last;
    break;
  }
```
----
本地成功了, 就放到服务器上, 向对应域名内添加如上规则, 并不能成功
![image](https://user-images.githubusercontent.com/19728934/42882904-9d520a42-8acc-11e8-8dcf-2d6d1286c829.png)
![image](https://user-images.githubusercontent.com/19728934/42883216-889d8d14-8acd-11e8-95e8-03189db85705.png)
我的 php7.0 配置中明明有引入 pathinfo

**Comment by tekintian** [comment]
你这个应该是rewrite没有生效，可以先放一个测试文件试试看，或者直接访问 index.php?s=/Admin/Login
